### ISSUE TITLE
HPX performance degrades with time since execution begins

### ISSUE THREAD

**Issue by dmarce1** [STEllAR-GROUP/hpx#1753]
In the runs where octotiger runs for a bit before crashing or locking up, I am noticing that the performance gets worse as time progresses. 

Example: http://s7.postimg.org/5x1kah1wb/degrade.png

This seems to be the case for every run I have looked at, each with 100 or 128 processors on SuperMIC. There is no computational reason that should be happening - the number of floating point operations required for each time-step is nearly constant.

**Comment by sithhell** [comment]
How do I run the code with a different number of timesteps?

**Comment by neutrino504** [comment]
The code executes forever until it crashes. Do you want to set a maximum number? The main loop is in main.cpp. Have you been able to execute it at all? You can change the maximum refinement level with MAX_LEVEL in defs.hpp

**Comment by sithhell** [comment]
Am 22.09.2015 5:14 nachm. schrieb "Neutrino" <notifications@github.com>:
>
> The code executes forever until it crashes. Do you want to set a maximum
number? The main loop is in main.cpp. Have you been able to execute it at
all? You can change the maximum refinement level with MAX_LEVEL in defs.hpp

Yes, im able to build and run the code. I was just wondering how you
obtained the numbers for the different time steps.

**Comment by sithhell** [comment]
@dmarce1, how do I get the output how long a single timestep took?

**Comment by dmarce1** [comment]
There should be a line of output for every timestep showing

step number - current time - timstep size - wallclock time for timestep

These same numbers will be in "step.dat"

**Comment by sithhell** [comment]
I was able to succesfully run your code with #1772 now. There were bunch of problems in your code as well. I'll open a PR ASAP (see #1752 for more information). What you can see is that I can't reproduce your regression in the wallclock time of the timesteps:
![step](https://cloud.githubusercontent.com/assets/53655/10162186/c86ada50-66a9-11e5-8845-cb71d6221466.png)

However, plotting dt, gives a similar graph than what you showed:
![dt](https://cloud.githubusercontent.com/assets/53655/10162223/2ca50108-66aa-11e5-8bc2-ac6d0f36a454.png)

**Comment by dmarce1** [comment]
I think if you replot the wall clock time plot with the yrange set to something like [1.5:2.0] you'll get a similar picture to what I got.

**Comment by sithhell** [comment]
You are most certainly correct. The yscale did make a misleading impression. So we see a slowdown of a factor of roughly 1.4. To give a better impression, I plotted the relative slowdown (omitting the peaks where the checkpoint data is being written:
![decrease](https://cloud.githubusercontent.com/assets/53655/10163768/5f39501e-66b5-11e5-8939-97ada3d32367.png)

So we are getting down to about 70% of the performance... Does this have to be caused by HPX or could this also be caused by the algorithm used (work imbalances etc.)?

**Comment by hkaiser** [comment]
We're currently investigating this issue in another application and we think to have some hints on what's causing this. I hope to have more information available soon.

**Comment by hkaiser** [comment]
This should be fixed once #1775 is merged.

**Comment by hkaiser** [comment]
@dmarce1 #1811 fixed another set of problems causing slowdown. Please report back if this issue can be closed now

**Comment by hkaiser** [comment]
@dmarce1 Can this be closed now? From what I understand these issues should have been solved by now.

**Comment by hkaiser** [comment]
I'm closing this now, please reopen, if appropriate.

**Comment by dmarce1** [comment]
I am still getting performance degradation over time. Here is a plot: 

http://s17.postimg.org/6h8qkbvn3/performance.png

This is with 64 nodes on SuperMIC

This is with a version of octotiger that doesn't rely on serialization of std::array, https://github.com/dmarce1/octotiger/commit/7214efefa48f01d1d1ec3dcd24b8631056c39b80

**Comment by dmarce1** [comment]
Here's a longer plot:

![performance](https://cloud.githubusercontent.com/assets/1951950/11957891/15f621cc-a88a-11e5-9f5b-3660cf51a2b9.png)


The little spikes aren't a problem, those are steps where octotiger outputs to the file system.  But as you can see the wall clock time increases linearly to a point and then levels off. There are small changes in the total load over the run as AMR refinement grids are created and destroyed, but this is less than +/- 10% of the starting load - not nearly enough to account for this.

Could this be a problem in octo-tiger itself and if so what would it look like?

On a positive note - this run represents the longest I have ever run octo-tiger using distributed HPX without a crash or freezeup.

**Comment by sithhell** [comment]
Is this with a release build?
Which column represents the wall clock time of a step?
Am 22.12.2015 4:03 nachm. schrieb "Dominic Marcello" <
notifications@github.com>:
>
> Here's a longer plot:
>
> The little spikes aren't a problem, those are steps where octotiger
outputs to the file system. But as you can see the wall clock time
increases linearly to a point and then levels off. There are small changes
in the total load over the run as AMR refinement grids are created and
destroyed, but this is less than +/- 10% of the starting load - not nearly
enough to account for this.
>
> Could this be a problem in octo-tiger itself and if so what would it look
like?
>
> On a positive note - this run represents the longest I have ever run
octo-tiger using distributed HPX without a crash or freezeup.

**Comment by dmarce1** [comment]
This is with a debug build. Each data point is one timestep, with the y-axis being the wall clock time for that timestep in seconds, and the x-axis being the number of the timestep since the start of the evolution. 

Its as if there is some resource not being freed.

**Comment by sithhell** [comment]
Am 22.12.2015 5:48 nachm. schrieb "Dominic Marcello" <
notifications@github.com>:
>
> This is with a debug build. Each data point is one timestep, with the
y-axis being the wall clock time for that timestep in seconds, and the
x-axis being the number of the timestep since the start of the evolution.

Sorry, i meant the output in octotiger...

**Comment by dmarce1** [comment]
My bad - Wall clock time is the 4th column in step.dat. The timestep number is the 1st column


Whatever is causing the issue doesn't appear to be taking up much memory. I started the run over and I've been tracking how much memory is used and it hasn't changed much while the wall clock time has already gone up to ~10 x the original step size.

**Comment by hkaiser** [comment]
Frankly, I wouldn't draw any conclusions from performance measurements done in debug-builds.
HPX is doing a lot of book-keeping and other additional things when compiled in debug-mode which might cause the slowdown you're seeing. Could you please verify whether the slowdown is still happening when run in release-mode?

**Comment by dmarce1** [comment]
I am running in release mode now and still getting the same problem.

**Comment by dmarce1** [comment]
Update-

I have been looking at performance counters and how they are changing with execution time for one timestep. I am resetting the counters with each time-step. This is what I have found:

Counters with a normalized increase over time similar to the normalized increase over time for wall clock per time-step:

/threads/count/cumulative-phases 
/threads/count/pending-accesses
/threads/count/pending-misses

Counters that increase over time but at a slower rate
/threads/count/cumulative
/threads/count/stack-recycles
/threads/count/stack-unbinds
/threads/count/stolen-from-pending

Counters that do not change much over time:
/threads/count/instantaneous/<all of them>
/threads/count/objects 

Counters that increase a little bit at first, then come back down, then go back up again
/threads/count/stolen-from-staged 
/threads/count/stolen-to-staged 

I have not tested any other counters. Can anyone suggest which might be the most useful?

**Comment by hkaiser** [comment]
When using the plot script I linked above there wouldn't be any need to reset counters (resetting might be tricky as it is a 'global' operation which does not take into account computational phases). 

For other counters you might want to look at: I'd suggest looking at action invocation counts: 

    /runtime/count/action_invocation@*
    /runtime/count/remote_action_invocation@*

which count all (local and remote) action invocations individually. Note that remote action invocations are counted as local as well (on the locality where they are run)

Also, can you provide a link to those graphs you described above? The increase in increments for those counters makes sense as all of them are related to thread execution. Everything hints at an overall increase of some operation counts. The action counters above might give us a better (higher level) insight.

**Comment by dmarce1** [comment]
I have found evidence of the culprit. When I turn off agas caching, the initial performance is of course a little worse - but it does not degrade with time.

**Comment by dmarce1** [comment]
Attached is a zip file with results from the agas cache performance counters when agas caching is turned "on".


[plots.zip](https://github.com/STEllAR-GROUP/hpx/files/78977/plots.zip)

Here is what appears to me to be the only plot of note:

![agas_time_cache_get_entry](https://cloud.githubusercontent.com/assets/1951950/12126449/e8eca9fc-b3b6-11e5-9d8d-5b0d0bcab5f9.png)

The relative increase in time it takes for "get_entry" to run is roughly proportional to the increase in wall clock per timestep over that same time period.

**Comment by hkaiser** [comment]
The first plot makes total sense, as the counter `/agas/time/cache/get_entry` is cumulative. I'd expect for it to go up linearly. Were you resetting counters while gathering that data?

**Comment by dmarce1** [comment]
Yes - I am resetting the counters every time-step. The plot should be roughly horizontal in that case, no?

**Comment by hkaiser** [comment]
Could you rerun without resetting counters, please? I'd like to exclude the possibility of problems related to that.

**Comment by dmarce1** [comment]
Here is the re-run without re-setting. Note I am using 'large' stacks, and output is turned on (it is turned off above). This is why there are spikes in the 'diff' plot. 

![agas_time_cache_get_entry_diff](https://cloud.githubusercontent.com/assets/1951950/12184156/346277b0-b559-11e5-8572-400881549a67.png)
![agas_time_cache_get_entry](https://cloud.githubusercontent.com/assets/1951950/12184155/34625c26-b559-11e5-8cc6-970f2100134c.png)

**Comment by hkaiser** [comment]
I think I know what's going on. @dmarce1 How many overall localities/cores were you running on for the latest graph above?

**Comment by dmarce1** [comment]
64 nodes, 20 cores a node, 1 locality per node,  20 threads a locality.

**Comment by dmarce1** [comment]
Is someone working on this?

**Comment by hkaiser** [comment]
Yes, I think I have a solution, working on it.

**Comment by hkaiser** [comment]
@dmarce1 reported today that he believes for the slowdown to have been fixed.
