### ISSUE TITLE
Broken links on http://stellar.cct.lsu.edu/2015/05/hpx-archives-now-on-gmane/

### ISSUE THREAD

**Issue by grantrostig** [STEllAR-GROUP/hpx#3681]
## Expected Behavior
Seeing the the two mail archives.  Or at least finding them on Gmane
http://stellar.cct.lsu.edu/2015/05/hpx-archives-now-on-gmane/

## Actual Behavior
Broken links are:
`Mailing Lists:
    hpx-users
    hpx-devel
` 
Also, searching for the lists on Gmane results in error message, under construction.

## Steps to Reproduce the Problem
Click on the two links or even try a search.
## Specifications
  - HPX Version: 1.2.0
  - Platform (compiler, OS): fedora29

**Comment by hkaiser** [comment]
@grantrostig yes, gmane is dead. try mail-archives instead (https://www.mail-archive.com/hpx-devel@stellar.cct.lsu.edu/ and https://www.mail-archive.com/hpx-users@stellar.cct.lsu.edu/)

**Comment by hkaiser** [comment]
The links have been fixed. Thanks for reporting.

**Comment by grantrostig** [comment]
Confirmed fixed. Thanks.

**Comment by grantrostig** [comment]
NOT FULLY FIXED.  Sorry, but the webpage should no longer refer to Gmane, unless the plan is to go back to that system.

**Comment by hkaiser** [comment]
>  I guess it does seem strange to update a old blog page.

That's the reason why I left it in place as much as possible.

**Comment by grantrostig** [comment]
I agree.  Confirmed Closed.
