### ISSUE TITLE
Configure of HPX project using CMake FetchContent fails

### ISSUE THREAD

**Issue by kordejong** [STEllAR-GROUP/hpx#4232]
## Expected Behavior

My project uses CMake's FetchContent module to fetch, configure and build HPX. Configuring and building my project should trigger a successful configure and build of HPX.

## Actual Behavior

Configuring of the HPX project fails with messages like this:

```
CMake Error: File /home/kor/development/project/hello_hpx/cmake/templates/global_module_header.hpp.in does not exist.
CMake Error at /tmp/hello_hpx/Debug-default/build/_deps/hpx-src/cmake/HPX_AddModule.cmake:102 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  /tmp/hello_hpx/Debug-default/build/_deps/hpx-src/libs/algorithms/CMakeLists.txt:126 (add_hpx_module)
```

## Steps to Reproduce the Problem

  1. git clone https://github.com/kordejong/hello_hpx.git
  1. ./debug_build.sh

## Specifications

I will attach a file with details and error messages.

  - HPX Version: 1.4.0-rc1
  - Platform (compiler, OS): Linux, gcc

**Comment by kordejong** [comment]
Output from running `debug_build.sh` on my machine:

[debug_build.txt](https://github.com/STEllAR-GROUP/hpx/files/3868880/debug_build.txt)

**Comment by aurianer** [comment]
@kordejong is that working for you ?

**Comment by kordejong** [comment]
Great, your update fixes the configure error! The build starts, but does not finish successfully. Here is the full output, again from running `debug_build.sh`.
[debug_build.txt](https://github.com/STEllAR-GROUP/hpx/files/3873553/debug_build.txt)

**Comment by aurianer** [comment]
That should be good now :)

**Comment by kordejong** [comment]
Building HPX with your latest commit gets me 26% into the build, but it then stops with this error message:

```
/tmp/hello_hpx/Debug-default/build/_deps/hpx-src/src/version.cpp:12:10: fatal error: hpx/config/config_strings.hpp: No such file or directory
 #include <hpx/config/config_strings.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
_deps/hpx-build/src/CMakeFiles/hpx.dir/build.make:140: recipe for target '_deps/hpx-build/src/CMakeFiles/hpx.dir/version.cpp.o' failed
```

**Comment by aurianer** [comment]
So I used your repo `hello_hpx` and it is configuring and building fine when using the `GIT_TAG` 560e3d06568 (latest commit on the PR) inside the `FetchContent_Declare`, did you update the tag used ?

**Comment by kordejong** [comment]
Yes, I used that same commit. I double-checked the HPX commit used in the build and it is indeed same (560e3d06568).

**Comment by kordejong** [comment]
I am new to using PRs, but everything looks OK in my local repository. `git show 560e3d0` outputs the same edits as shown here: https://github.com/STEllAR-GROUP/hpx/pull/4233/files

**Comment by kordejong** [comment]
The missing `hpx/config/config_strings.hpp` appears to be generated during the build and put in `hpx-build/hpx/config/config_strings.hpp`. Is `hpx-build` added to the list of directories the compiler needs to search for headers?

I know it works for you and it doesn't for me, but I just got rid of all my local HPX sources, and cloned fresh sources and your PR. Configuring works fine, but after 26% into the build it fails to build `version.cpp` with the above error message.

Did you run my `debug_build.sh`, or did you maybe build from the build directory? Maybe that matters. In my build script configuring and building the project happens from outside the build directory.

**Comment by aurianer** [comment]
Could you make me the same file with the whole build output like before ?

**Comment by kordejong** [comment]
[debug_build.txt](https://github.com/STEllAR-GROUP/hpx/files/3878933/debug_build.txt)

**Comment by aurianer** [comment]
Thanks, that should be solved now, sorry for the delay my `grep` for the old cmake variables was not as exhaustive as I thought ^^

**Comment by kordejong** [comment]
I just tested your new commit a81289b0e66. The build of `version.cpp` still fails, but with a slightly different error:

```
In file included from /tmp/hello_hpx/Debug-default/build/_deps/hpx-src/src/version.cpp:12:0:
/tmp/hello_hpx/Debug-default/build/_deps/hpx-build/hpx/config/config_strings.hpp:12:10: fatal error: hpx/config/config_defines_strings_modules.hpp: No such file or directory
 #include <hpx/config/config_defines_strings_modules.hpp>                        
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                        
```

I think we are getting close ;-)

**Comment by aurianer** [comment]
Haha sorry ^^ now ?

**Comment by kordejong** [comment]
Yes, the build succeeds now with your commit ab4f095dd21. Very good! I guess this issue can be closed now.
