### ISSUE TITLE
Application runs even if `--hpx:help` is specified

### ISSUE THREAD

**Issue by albestro** [STEllAR-GROUP/hpx#4317]
## Expected Behavior

If one of the options triggering the helper message (e.g. `-h`, `--hpx:help`) is specified, the application should not run.

## Actual Behavior

It prints the helper message, and then it runs the application.

## Steps to Reproduce the Problem

It seems that the `resource::partitioner` initialization does not manage correctly the help. By removing it and passing arguments just to `hpx::init` everything work as expected.

```cpp
#include <iostream>

#include <hpx/hpx.hpp>
#include <hpx/hpx_init.hpp>

int hpx_main(hpx::program_options::variables_map& vm)
{
    std::cout << "app run!" << std::endl;
    return hpx::finalize();
}

int main(int argc, char** argv)
{
    using namespace hpx::program_options;

    options_description
       desc_commandline("Usage: " HPX_APPLICATION_STRING " [options]");

    desc_commandline.add_options()
        ( "n"
        , value<std::uint64_t>()->default_value(13)
        , "n generic parameter")
        ;

    hpx::resource::partitioner rp(desc_commandline, argc, argv);

    std::cout << "before hpx init" << std::endl;

    return hpx::init(hpx_main, desc_commandline, argc, argv);
}
```

## Specifications
  - HPX Version: 1.4.0
  - Platform (compiler, OS): gcc, linux

**Comment by hkaiser** [comment]
@albestro we've had contradictory opinions from users on this issue before. In the end we decided to go with what we have today and have added `--hpx:exit` to force the behavior you are asking for. This command line option will make your application exit right after printing the help message (if used in conjunction with `--hpx:help`). 

The motivation for this solution was the fact, that there are other options that possibly print additional information at startup (like `--hpx:dump-config`), and it was not clear for those whether and immediate exit was the appropriate expected behavior.

I tend to suggest to close this request as 'will not fix'. What do others think?

**Comment by albestro** [comment]
Thank you for your reply @hkaiser !

I didn't know about the `--hpx:exit` option, thank you for the hint.

What looks strange to me is that the behavior changes if I use the resource partitioner or not: if I just use the `hpx::init` call it works as expected, even without `--hpx:exit`.

Is it what you intended to do or did you expect that in every case the `--hpx:exit` option has to be specified to make the program exit after the help message?

**Comment by hkaiser** [comment]
> What looks strange to me is that the behavior changes if I use the resource partitioner or not: if I just use the hpx::init call it works as expected, even without --hpx:exit.
> Is it what you intended to do or did you expect that in every case the --hpx:exit option has to be specified to make the program exit after the help message?

This is definitely something I didn't expect (or know about). The behavior has to be consistent.

**Comment by hkaiser** [comment]
@albestro This has been addressed now. Please verify if the patch fixes the issues you reported.

**Comment by albestro** [comment]
Hi @hkaiser,
I've tried it with the code I reported in the issue and the problem is not solved yet.
Then I tried your test, and that one works!

By a quick look, I see that the difference in the two sources is that you are passing the resource partitioner instance to the `hpx::init`.

P.S. @msimberg already told me that things are moving on the resource partitioner side.

**Comment by hkaiser** [comment]
@albestro yes, we still need to make sure that the correct version of `hpx::init` is being used if the resource partitioner is initialized separately. That would have given you a better clue. Thanks!
