### ISSUE TITLE
HPX 1.9.1 does not compile on Fedora with ‘#pragma message:  [Parallel STL message]: "Vectorized algorithm unimplemented, redirected to serial

### ISSUE THREAD

**Issue by diehlpk** [STEllAR-GROUP/hpx#6437]
## Expected Behavior

HPX should compile on Fedora rawhide.

## Actual Behavior

```
hpx-1.9.1/libs/full/collectives/src/detail/communication_set_node.cpp
In file included from /usr/include/c++/14/x86_64-redhat-linux/bits/c++config.h:2736,
                 from /usr/include/c++/14/type_traits:38,
                 from /builddir/build/BUILD/hpx-1.9.1/libs/core/config/include/hpx/config/move.hpp:17,
                 from /builddir/build/BUILD/hpx-1.9.1/libs/core/config/include/hpx/config.hpp:29,
                 from /builddir/build/BUILD/hpx-1.9.1/libs/full/collectives/src/detail/communication_set_node.cpp:7:
/usr/include/c++/14/pstl/algorithm_impl.h: In function ‘_RandomAccessIterator __pstl::__internal::__brick_unique(_RandomAccessIterator, _RandomAccessIterator, _BinaryPredicate, std::true_type)’:
/usr/include/c++/14/pstl/algorithm_impl.h:1219:5: note: ‘#pragma message:  [Parallel STL message]: "Vectorized algorithm unimplemented, redirected to serial"’
 1219 |     _PSTL_PRAGMA_MESSAGE("Vectorized algorithm unimplemented, redirected to serial");
      |     ^~~~~~~~~~~~~~~~~~~~
/usr/include/c++/14/pstl/algorithm_impl.h: In function ‘_RandomAccessIterator __pstl::__internal::__brick_partition(_RandomAccessIterator, _RandomAccessIterator, _UnaryPredicate, std::true_type)’:
/usr/include/c++/14/pstl/algorithm_impl.h:1929:5: note: ‘#pragma message:  [Parallel STL message]: "Vectorized algorithm unimplemented, redirected to serial"’
 1929 |     _PSTL_PRAGMA_MESSAGE("Vectorized algorithm unimplemented, redirected to serial");
      |     ^~~~~~~~~~~~~~~~~~~~
/usr/include/c++/14/pstl/algorithm_impl.h: In function ‘_RandomAccessIterator __pstl::__internal::__brick_stable_partition(_RandomAccessIterator, _RandomAccessIterator, _UnaryPredicate, std::true_type)’:
/usr/include/c++/14/pstl/algorithm_impl.h:2029:5: note: ‘#pragma message:  [Parallel STL message]: "Vectorized algorithm unimplemented, redirected to serial"’
 2029 |     _PSTL_PRAGMA_MESSAGE("Vectorized algorithm unimplemented, redirected to serial");
      |     ^~~~~~~~~~~~~~~~~~~~
/usr/include/c++/14/pstl/algorithm_impl.h: In function ‘_RandomAccessIterator3 __pstl::__internal::__brick_merge(_RandomAccessIterator1, _RandomAccessIterator1, _RandomAccessIterator2, _RandomAccessIterator2, _RandomAccessIterator3, _Compare, std::true_type)’:
/usr/include/c++/14/pstl/algorithm_impl.h:2715:5: note: ‘#pragma message:  [Parallel STL message]: "Vectorized algorithm unimplemented, redirected to serial"’
 2715 |     _PSTL_PRAGMA_MESSAGE("Vectorized algorithm unimplemented, redirected to serial");
      |     ^~~~~~~~~~~~~~~~~~~~
/usr/include/c++/14/pstl/algorithm_impl.h: In function ‘void __pstl::__internal::__brick_inplace_merge(_RandomAccessIterator, _RandomAccessIterator, _RandomAccessIterator, _Compare, std::true_type)’:
/usr/include/c++/14/pstl/algorithm_impl.h:2764:5: note: ‘#pragma message:  [Parallel STL message]: "Vectorized algorithm unimplemented, redirected to serial"’
 2764 |     _PSTL_PRAGMA_MESSAGE("Vectorized algorithm unimplemented, redirected to serial")
      |     ^~~~~~~~~~~~~~~~~~~~
/usr/include/c++/14/pstl/algorithm_impl.h: In function ‘_OutputIterator __pstl::__internal::__brick_set_union(_RandomAccessIterator1, _RandomAccessIterator1, _RandomAccessIterator2, _RandomAccessIterator2, _OutputIterator, _Compare, std::true_type)’:
/usr/include/c++/14/pstl/algorithm_impl.h:3141:5: note: ‘#pragma message:  [Parallel STL message]: "Vectorized algorithm unimplemented, redirected to serial"’
 3141 |     _PSTL_PRAGMA_MESSAGE("Vectorized algorithm unimplemented, redirected to serial");
      |     ^~~~~~~~~~~~~~~~~~~~
/usr/include/c++/14/pstl/algorithm_impl.h: In function ‘_RandomAccessIterator3 __pstl::__internal::__brick_set_intersection(_RandomAccessIterator1, _RandomAccessIterator1, _RandomAccessIterator2, _RandomAccessIterator2, _RandomAccessIterator3, _Compare, std::true_type)’:
/usr/include/c++/14/pstl/algorithm_impl.h:3202:5: note: ‘#pragma message:  [Parallel STL message]: "Vectorized algorithm unimplemented, redirected to serial"’
 3202 |     _PSTL_PRAGMA_MESSAGE("Vectorized algorithm unimplemented, redirected to serial");
      |     ^~~~~~~~~~~~~~~~~~~~
/usr/include/c++/14/pstl/algorithm_impl.h: In function ‘_RandomAccessIterator3 __pstl::__internal::__brick_set_difference(_RandomAccessIterator1, _RandomAccessIterator1, _RandomAccessIterator2, _RandomAccessIterator2, _RandomAccessIterator3, _Compare, std::true_type)’:
/usr/include/c++/14/pstl/algorithm_impl.h:3298:5: note: ‘#pragma message:  [Parallel STL message]: "Vectorized algorithm unimplemented, redirected to serial"’
 3298 |     _PSTL_PRAGMA_MESSAGE("Vectorized algorithm unimplemented, redirected to serial");
      |     ^~~~~~~~~~~~~~~~~~~~
/usr/include/c++/14/pstl/algorithm_impl.h: In function ‘_RandomAccessIterator3 __pstl::__internal::__brick_set_symmetric_difference(_RandomAccessIterator1, _RandomAccessIterator1, _RandomAccessIterator2, _RandomAccessIterator2, _RandomAccessIterator3, _Compare, std::true_type)’:
/usr/include/c++/14/pstl/algorithm_impl.h:3390:5: note: ‘#pragma message:  [Parallel STL message]: "Vectorized algorithm unimplemented, redirected to serial"’
 3390 |     _PSTL_PRAGMA_MESSAGE("Vectorized algorithm unimplemented, redirected to serial");
      |     ^~~~~~~~~~~~~~~~~~~~
gmake[2]: Leaving directory '/builddir/build/BUILD/hpx-1.9.1/x86_64-redhat-linux-gnu-serial'
[ 42%] Built target hpx_collectives
gmake[1]: Leaving directory '/builddir/build/BUILD/hpx-1.9.1/x86_64-redhat-linux-gnu-serial'
gmake: *** [Makefile:149: all] Error 2
```

Error log: https://bugzilla-attachments.redhat.com/attachment.cgi?id=2012222

## Steps to Reproduce the Problem

... Please be as specific as possible while describing how to reproduce your problem.

  1. Build HPX 1.9.1 on Fedora's build system

## Specifications

... Please describe your environment

  - HPX Version:
  - Platform (compiler, OS): fedora rawhide, GCC 14

**Comment by hkaiser** [comment]
@diehlpk could you link the full error log please?

**Comment by diehlpk** [comment]
https://kojipkgs.fedoraproject.org//work/tasks/9795/112299795/build.log

**Comment by hkaiser** [comment]
> https://kojipkgs.fedoraproject.org//work/tasks/9795/112299795/build.log

Here is a patch fixing this issue:
```diff
diff --git a/libs/core/executors/include/hpx/executors/restricted_thread_pool_executor.hpp b/libs/core/executors/include/hpx/executors/restricted_thread_pool_executor.hpp
index 6404f60243d..1073292d0f4 100644
--- a/libs/core/executors/include/hpx/executors/restricted_thread_pool_executor.hpp
+++ b/libs/core/executors/include/hpx/executors/restricted_thread_pool_executor.hpp
@@ -242,7 +242,7 @@ namespace hpx::parallel::execution {
         /// \endcond
 
     private:
-        std::uint16_t const first_thread_;
+        std::uint16_t first_thread_;
         mutable std::atomic<std::size_t> os_thread_;
 
         embedded_executor exec_;
```

**Comment by andreichalapco** [comment]
I'm still getting the errors, altough building from stable master branch

**Comment by hkaiser** [comment]
> I'm still getting the errors, altough building from stable master branch

I don't think that we will patch V1.9.1 without explicit support. Please get in contact if you would like to discuss options.

**Comment by andreichalapco** [comment]
but I'm on the master branch ... ( that should be > 1.10) or?

**Comment by hkaiser** [comment]
> but I'm on the master branch ... ( that should be > 1.10) or?

I think this issue is resolved on V1.10.0. If not, please let us know.

**Comment by andreichalapco** [comment]
The fix mentioned above is in the code ... sadly I still get the warnings
